// This file is a bridge during migration.
// All exports delegate to the new domain-scoped storage layer via the compat shim.
// Once all consumers import from 'src/lib/storage/index.js' directly, delete this file.
export {
  saveIdea,
  getIdeas,
  subscribeToIdeas,
  setIdeaArchived,
  setIdeaHidden,
  setIdeaPinned,
  setIdeaCategories,
  deleteIdea,
  updateIdeaText,
  updateIdeaPriority,
  getCategories,
  getCategoryPalette,
  setCategoryColor,
  setCategoryVisibility,
  renameCategory,
  subscribeToCategorySettings,
  trackCategoryUsage,
  getCategoriesByRecentUsage,
  subscribeToPageNotes,
  savePageNote,
  deletePageNote,
  subscribeToNoteFolders,
  saveNoteFolder,
  deleteNoteFolder,
  loadCanvasLayout,
  saveCanvasLayout,
  subscribeToCanvasLayout,
  subscribeToNotes,
  addNote,
  deleteNote,
  updateNoteText,
  getNotesFromLocal,
  getNoteCount,
  addComment,
  subscribeToComments,
  getPendingMutationCount,
  flushPendingMutations,
} from './storage/compat.js';
