// src/lib/demo/seed-data.js

const now = Date.now();
const DAY = 86_400_000;

// Helper: date N days ago
const daysAgo = (n) => now - n * DAY;

// ── Ideas ──────────────────────────────────────────────────────

export const SEED_IDEAS = [
  {
    id: 'demo-idea-1',
    text: 'Build a personal portfolio website',
    category: 'Projects',
    categories: ['Projects'],
    tags: ['web', 'portfolio'],
    priority: 'urgent',
    createdAt: daysAgo(14),
    archived: false,
    hidden: false,
    pinned: true,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-2',
    text: 'Create a habit tracking app with streaks and reminders',
    category: 'Projects',
    categories: ['Projects', 'Learning'],
    tags: ['mobile', 'productivity'],
    priority: 'high',
    createdAt: daysAgo(12),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-3',
    text: 'Design a reading list dashboard',
    category: 'Projects',
    categories: ['Projects', 'Creative'],
    tags: ['design', 'books'],
    priority: 'medium',
    createdAt: daysAgo(11),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-4',
    text: 'Write a short story about time travel',
    category: 'Creative',
    categories: ['Creative'],
    tags: ['writing', 'fiction'],
    priority: 'medium',
    createdAt: daysAgo(10),
    archived: false,
    hidden: false,
    pinned: true,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-5',
    text: 'Learn watercolor painting basics',
    category: 'Creative',
    categories: ['Creative'],
    tags: ['art', 'hobby'],
    priority: 'low',
    createdAt: daysAgo(9),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-6',
    text: 'Start a photo-a-day challenge for 30 days',
    category: 'Creative',
    categories: ['Creative', 'Life'],
    tags: ['photography', 'challenge'],
    priority: 'low',
    createdAt: daysAgo(8),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-7',
    text: 'Deep dive into WebSocket protocols',
    category: 'Learning',
    categories: ['Learning'],
    tags: ['networking', 'backend'],
    priority: 'high',
    createdAt: daysAgo(7),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-8',
    text: "Read 'Designing Data-Intensive Applications'",
    category: 'Learning',
    categories: ['Learning'],
    tags: ['books', 'systems'],
    priority: 'urgent',
    createdAt: daysAgo(6),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-9',
    text: 'Take an online course on system design',
    category: 'Learning',
    categories: ['Learning'],
    tags: ['career', 'architecture'],
    priority: 'medium',
    createdAt: daysAgo(5),
    archived: true,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-10',
    text: 'Plan a weekend hiking trip to the mountains',
    category: 'Life',
    categories: ['Life'],
    tags: ['outdoors', 'travel'],
    priority: 'high',
    createdAt: daysAgo(4),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-11',
    text: 'Try a new recipe every week this month',
    category: 'Life',
    categories: ['Life'],
    tags: ['cooking', 'challenge'],
    priority: 'low',
    createdAt: daysAgo(3),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-12',
    text: 'Organize the garage — donate old gear',
    category: 'Life',
    categories: ['Life'],
    tags: ['home', 'declutter'],
    priority: '',
    createdAt: daysAgo(2),
    archived: false,
    hidden: true,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-13',
    text: 'Sketch out a logo for the side project',
    category: 'Random',
    categories: ['Random', 'Creative'],
    tags: ['design'],
    priority: 'low',
    createdAt: daysAgo(1),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-14',
    text: 'Set up CI to run tests on every pull request',
    category: 'Projects',
    categories: ['Projects'],
    tags: ['dev'],
    priority: 'medium',
    createdAt: daysAgo(9),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-15',
    text: 'Write a README with screenshots for the repo',
    category: 'Projects',
    categories: ['Projects'],
    tags: ['docs'],
    priority: 'low',
    createdAt: daysAgo(6),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-16',
    text: 'Record a short demo video of the app',
    category: 'Creative',
    categories: ['Creative'],
    tags: ['video'],
    priority: 'medium',
    createdAt: daysAgo(7),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-17',
    text: 'Try a watercolor series of city skylines',
    category: 'Creative',
    categories: ['Creative'],
    tags: ['art'],
    priority: 'low',
    createdAt: daysAgo(4),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-18',
    text: 'Finish the TypeScript generics course',
    category: 'Learning',
    categories: ['Learning'],
    tags: ['typescript'],
    priority: 'high',
    createdAt: daysAgo(5),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-19',
    text: 'Read one research paper every week',
    category: 'Learning',
    categories: ['Learning'],
    tags: ['habit'],
    priority: 'medium',
    createdAt: daysAgo(3),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-20',
    text: 'Plan a surprise dinner for the anniversary',
    category: 'Life',
    categories: ['Life'],
    tags: ['family'],
    priority: 'urgent',
    createdAt: daysAgo(2),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-21',
    text: 'What if notes could be pinned to a map?',
    category: 'Random',
    categories: ['Random'],
    tags: ['wild-card'],
    priority: '',
    createdAt: daysAgo(1),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-22',
    text: 'Draft the quarterly roadmap for the team',
    category: 'Work',
    categories: ['Work'],
    tags: ['planning'],
    priority: 'urgent',
    createdAt: daysAgo(8),
    archived: false,
    hidden: false,
    pinned: true,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-23',
    text: 'Prepare talking points for Monday standup',
    category: 'Work',
    categories: ['Work'],
    tags: ['meetings'],
    priority: 'medium',
    createdAt: daysAgo(2),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-24',
    text: 'Collect customer feedback from support tickets',
    category: 'Work',
    categories: ['Work'],
    tags: ['research'],
    priority: 'high',
    createdAt: daysAgo(6),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-25',
    text: 'Automate the weekly status report',
    category: 'Work',
    categories: ['Work'],
    tags: ['automation'],
    priority: 'medium',
    createdAt: daysAgo(4),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-26',
    text: 'Book an annual checkup',
    category: 'Health',
    categories: ['Health'],
    tags: ['appointments'],
    priority: 'high',
    createdAt: daysAgo(10),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-27',
    text: 'Try a 20-minute morning stretch routine',
    category: 'Health',
    categories: ['Health'],
    tags: ['habit'],
    priority: 'medium',
    createdAt: daysAgo(5),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-28',
    text: 'Meal prep lunches for the work week',
    category: 'Health',
    categories: ['Health'],
    tags: ['food'],
    priority: 'low',
    createdAt: daysAgo(3),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-29',
    text: 'Research train routes for a Japan trip',
    category: 'Travel',
    categories: ['Travel'],
    tags: ['japan', 'planning'],
    priority: 'medium',
    createdAt: daysAgo(12),
    archived: false,
    hidden: false,
    pinned: true,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-30',
    text: 'Make a packing checklist template',
    category: 'Travel',
    categories: ['Travel'],
    tags: ['lists'],
    priority: 'low',
    createdAt: daysAgo(6),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
  {
    id: 'demo-idea-31',
    text: 'Find a cabin for a weekend getaway',
    category: 'Travel',
    categories: ['Travel'],
    tags: ['getaway'],
    priority: 'high',
    createdAt: daysAgo(1),
    archived: false,
    hidden: false,
    pinned: false,
    userId: 'demo-user',
  },
];

// ── Category Palette ───────────────────────────────────────────

export const SEED_CATEGORY_PALETTE = {
  Projects:  { color: '#42a5f5', visible: true },
  Creative:  { color: '#ab47bc', visible: true },
  Learning:  { color: '#66bb6a', visible: true },
  Life:      { color: '#ef5350', visible: true },
  Random:    { color: '#ffa726', visible: true },
  Work:      { color: '#26c6da', visible: true },
  Health:    { color: '#9ccc65', visible: true },
  Travel:    { color: '#ec407a', visible: true },
};

// ── Canvas Layout ──────────────────────────────────────────────

export const SEED_CANVAS_LAYOUT = {
  cards: [
    // Build & Make
    { categoryName: 'Projects', x: 80,  y: 120 },
    { categoryName: 'Creative', x: 440, y: 120 },
    { categoryName: 'Work',     x: 800, y: 120 },
    // Growth
    { categoryName: 'Learning', x: 80,  y: 680 },
    { categoryName: 'Health',   x: 440, y: 680 },
    // Everyday Life
    { categoryName: 'Life',     x: 80,  y: 1240 },
    { categoryName: 'Travel',   x: 440, y: 1240 },
    { categoryName: 'Random',   x: 800, y: 1240 },
  ],
  headers: [
    { id: 'demo-header-1', text: 'Build & Make',  x: 80, y: 40 },
    { id: 'demo-header-2', text: 'Growth',        x: 80, y: 600 },
    { id: 'demo-header-3', text: 'Everyday Life', x: 80, y: 1160 },
  ],
  viewport: { panX: 0, panY: 0, zoom: 1 },
};

// ── Page Notes ─────────────────────────────────────────────────

export const SEED_NOTE_FOLDERS = [
  {
    id: 'demo-folder-1',
    name: 'Weekend Plans',
    sortOrder: 0,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    userId: 'demo-user',
  },
];

export const SEED_PAGE_NOTES = [
  {
    id: 'demo-note-1',
    title: 'Ideas for the weekend',
    content: '<p>Things to check out this Saturday:</p><ul><li>Farmers market downtown</li><li>New trail at the state park</li><li>Try that ramen place on 5th</li></ul>',
    folderId: 'demo-folder-1',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
    userId: 'demo-user',
  },
  {
    id: 'demo-note-2',
    title: 'Book recommendations',
    content: '<p>From the team chat:</p><ul><li>Designing Data-Intensive Applications</li><li>The Pragmatic Programmer</li><li>Staff Engineer by Will Larson</li></ul>',
    folderId: null,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
    userId: 'demo-user',
  },
  {
    id: 'demo-note-3',
    title: 'Project kickoff notes',
    content: '<p>Key decisions from the kickoff:</p><p>Stack: Vite + vanilla JS for speed. Firebase for auth and data. Mobile via Capacitor.</p><p>MVP scope: capture, review, canvas.</p>',
    folderId: null,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(8),
    userId: 'demo-user',
  },
];

// ── Thread Notes (comments on ideas) ───────────────────────────

export const SEED_THREAD_NOTES = {
  'demo-idea-1': [
    {
      id: 'demo-thread-1',
      text: 'Should use a dark theme to match the app aesthetic',
      createdAt: daysAgo(13),
      userId: 'demo-user',
    },
    {
      id: 'demo-thread-2',
      text: 'Check out Astro or plain HTML — keep it simple',
      createdAt: daysAgo(12),
      userId: 'demo-user',
    },
  ],
  'demo-idea-4': [
    {
      id: 'demo-thread-3',
      text: 'Maybe a paradox where the character meets their future self?',
      createdAt: daysAgo(9),
      userId: 'demo-user',
    },
  ],
};

export const SEED_TODOS = [
  { id: 'demo-todo-1', slot: 'morning', text: 'Review weekend plans', completed: true, sortOrder: 0, createdAt: daysAgo(1), userId: 'demo-user' },
  { id: 'demo-todo-2', slot: 'morning', text: 'Jot down new app ideas', completed: false, sortOrder: 1, createdAt: daysAgo(1), userId: 'demo-user' },
  { id: 'demo-todo-3', slot: 'afternoon', text: 'Sort ideas into categories', completed: false, sortOrder: 2, createdAt: daysAgo(1), userId: 'demo-user' },
  { id: 'demo-todo-4', slot: 'evening', text: 'Read a chapter of my book', completed: false, sortOrder: 3, createdAt: daysAgo(1), userId: 'demo-user' },
];
